import { CustomerFeedbackType } from "@/lib/types/customer-feedback-types";
import { NextResponse } from "next/server";

export async function GET(req: Request) {
  
  const customerFeedbackMockData:CustomerFeedbackType[] = [
    {name: "Klein Moretti",
    imagePath: "/images/png/klein_hat.png",
    imageAlt: "customer profile image",
    feedback: "The T-Shirt looks great! That would be part of my favorites",
    quoteUpIconPath: "/icons/svg/double-quotes-up.svg",
    quoteUpIconAlt: "double quotes up icon",
    quoteDownIconPath: "/icons/svg/double-quotes-down.svg",
    quoteDownIconAlt: "double quotes down icon",
    starRatingWithoutColorIconPath: "/icons/svg/star-no-color.svg",
    starRatingWithoutColorIconAlt: "star without color icon",
    starRatingWithColorIconPath: "/icons/svg/star-color.svg",
    starRatingWithColorIconAlt: "star with color icon",
    feedbackDate: "4-11-2025",
    },
    {name: "Arthur Leywin",
    imagePath: "/images/png/arthur_leywin_.png",
    imageAlt: "customer profile image",
    feedback: "This is my second purchase from your store, and I am very satisfied with the quality and design of the T-Shirt.",
    quoteUpIconPath: "/icons/svg/double-quotes-up.svg",
    quoteUpIconAlt: "double quotes up icon",
    quoteDownIconPath: "/icons/svg/double-quotes-down.svg",
    quoteDownIconAlt: "double quotes down icon",
    starRatingWithoutColorIconPath: "/icons/svg/star-no-color.svg",
    starRatingWithoutColorIconAlt: "star without color icon",
    starRatingWithColorIconPath: "/icons/svg/star-color.svg",
    starRatingWithColorIconAlt: "star with color icon",
    feedbackDate: "4-11-2025",
    },
    {name: "William James Moriarty",
    imagePath: "/images/png/william_james_moriarty.png",
    imageAlt: "customer profile image",
    feedback: "This T-Shirt exceeded my expectations! The fabric is soft and comfortable, and the print is vibrant and durable.",
    quoteUpIconPath: "/icons/svg/double-quotes-up.svg",
    quoteUpIconAlt: "double quotes up icon",
    quoteDownIconPath: "/icons/svg/double-quotes-down.svg",
    quoteDownIconAlt: "double quotes down icon",
    starRatingWithoutColorIconPath: "/icons/svg/star-no-color.svg",
    starRatingWithoutColorIconAlt: "star without color icon",
    starRatingWithColorIconPath: "/icons/svg/star-color.svg",
    starRatingWithColorIconAlt: "star with color icon",
    feedbackDate: "4-11-2025",
    },
    {name: "Asta",
    imagePath: "/images/png/asta.png",
    imageAlt: "customer profile image",
    feedback: "I like the design of the T-Shirt, it's unique and eye-catching. I've received many compliments on it.",
    quoteUpIconPath: "/icons/svg/double-quotes-up.svg",
    quoteUpIconAlt: "double quotes up icon",
    quoteDownIconPath: "/icons/svg/double-quotes-down.svg",
    quoteDownIconAlt: "double quotes down icon",
    starRatingWithoutColorIconPath: "/icons/svg/star-no-color.svg",
    starRatingWithoutColorIconAlt: "star without color icon",
    starRatingWithColorIconPath: "/icons/svg/star-color.svg",
    starRatingWithColorIconAlt: "star with color icon",
    feedbackDate: "4-11-2025",
    },
    {name: "Ayanokoji",
    imagePath: "/images/png/ayanokoji.png",
    imageAlt: "customer profile image",
    feedback: "The design stands out enough to draw attention. People seem to notice it, though I don’t particularly mind either way.",
    quoteUpIconPath: "/icons/svg/double-quotes-up.svg",
    quoteUpIconAlt: "double quotes up icon",
    quoteDownIconPath: "/icons/svg/double-quotes-down.svg",
    quoteDownIconAlt: "double quotes down icon",
    starRatingWithoutColorIconPath: "/icons/svg/star-no-color.svg",
    starRatingWithoutColorIconAlt: "star without color icon",
    starRatingWithColorIconPath: "/icons/svg/star-color.svg",
    starRatingWithColorIconAlt: "star with color icon",
    feedbackDate: "4-11-2025",
    },
    {name: "Sungjinwoo",
    imagePath: "/images/png/sungjinwoo.png",
    imageAlt: "customer profile image",
    feedback: "The shirt turned out better than I thought. Comfortable fabric, and the print looks like it’ll last.",
    quoteUpIconPath: "/icons/svg/double-quotes-up.svg",
    quoteUpIconAlt: "double quotes up icon",
    quoteDownIconPath: "/icons/svg/double-quotes-down.svg",
    quoteDownIconAlt: "double quotes down icon",
    starRatingWithoutColorIconPath: "/icons/svg/star-no-color.svg",
    starRatingWithoutColorIconAlt: "star without color icon",
    starRatingWithColorIconPath: "/icons/svg/star-color.svg",
    starRatingWithColorIconAlt: "star with color icon",
    feedbackDate: "4-11-2025",
    },
    {name: "Senku Ishigami",
    imagePath: "/images/png/senku_ishigami.png",
    imageAlt: "customer profile image",
    feedback: "The fabric has an excellent texture—soft enough for comfort, yet durable for long-term use! And that print? Top-notch quality, vibrant pigments that won’t fade easily. Ten billion percent satisfied!",
    quoteUpIconPath: "/icons/svg/double-quotes-up.svg",
    quoteUpIconAlt: "double quotes up icon",
    quoteDownIconPath: "/icons/svg/double-quotes-down.svg",
    quoteDownIconAlt: "double quotes down icon",
    starRatingWithoutColorIconPath: "/icons/svg/star-no-color.svg",
    starRatingWithoutColorIconAlt: "star without color icon",
    starRatingWithColorIconPath: "/icons/svg/star-color.svg",
    starRatingWithColorIconAlt: "star with color icon",
    feedbackDate: "4-11-2025",
    },
    {name: "Shinra Kusakabe",
    imagePath: "/images/png/shinra_kusakabe.png",
    imageAlt: "customer profile image",
    feedback: "This T-shirt’s awesome! Super comfy, and the design really pops. Kinda makes me wanna smile… heh.",
    quoteUpIconPath: "/icons/svg/double-quotes-up.svg",
    quoteUpIconAlt: "double quotes up icon",
    quoteDownIconPath: "/icons/svg/double-quotes-down.svg",
    quoteDownIconAlt: "double quotes down icon",
    starRatingWithoutColorIconPath: "/icons/svg/star-no-color.svg",
    starRatingWithoutColorIconAlt: "star without color icon",
    starRatingWithColorIconPath: "/icons/svg/star-color.svg",
    starRatingWithColorIconAlt: "star with color icon",
    feedbackDate: "4-11-2025",
    },
  ] 

  return NextResponse.json({
    message: "fetched successfully!",
    customerFeedbackMockData
  });
}