import { CustomerFeedbackType } from "../types/customer-feedback-types";

export const CustomerFeedbackValue: CustomerFeedbackType[] = [
    {name: "Klein Moretti",
    imagePath: "/images/png/klein_hat.png",
    imageAlt: "customer profile image",
    feedback: "The T-Shirt looks great! That would be part of my favorites",
    quoteUpIconPath: "/icons/svg/double-quotes-up.svg",
    quoteUpIconAlt: "double quotes up icon",
    quoteDownIconPath: "/icons/svg/double-quotes-down.svg",
    quoteDownIconAlt: "double quotes down icon",
    starRatingWithoutColorIconPath: "/icons/svg/star-no-color.svg",
    starRatingWithoutColorIconAlt: "star without color icon",
    starRatingWithColorIconPath: "/icons/svg/star-color.svg",
    starRatingWithColorIconAlt: "star with color icon",
    },
    {name: "Arthur Leywin",
    imagePath: "/images/png/arthur_leywin_.png",
    imageAlt: "customer profile image",
    feedback: "This is my second purchase from your store, and I am very satisfied with the quality and design of the T-Shirt.",
    quoteUpIconPath: "/icons/svg/double-quotes-up.svg",
    quoteUpIconAlt: "double quotes up icon",
    quoteDownIconPath: "/icons/svg/double-quotes-down.svg",
    quoteDownIconAlt: "double quotes down icon",
    starRatingWithoutColorIconPath: "/icons/svg/star-no-color.svg",
    starRatingWithoutColorIconAlt: "star without color icon",
    starRatingWithColorIconPath: "/icons/svg/star-color.svg",
    starRatingWithColorIconAlt: "star with color icon",
    },
    {name: "William James Moriarty",
    imagePath: "/images/png/william_james_moriarty.png",
    imageAlt: "customer profile image",
    feedback: "This T-Shirt exceeded my expectations! The fabric is soft and comfortable, and the print is vibrant and durable.",
    quoteUpIconPath: "/icons/svg/double-quotes-up.svg",
    quoteUpIconAlt: "double quotes up icon",
    quoteDownIconPath: "/icons/svg/double-quotes-down.svg",
    quoteDownIconAlt: "double quotes down icon",
    starRatingWithoutColorIconPath: "/icons/svg/star-no-color.svg",
    starRatingWithoutColorIconAlt: "star without color icon",
    starRatingWithColorIconPath: "/icons/svg/star-color.svg",
    starRatingWithColorIconAlt: "star with color icon",
    },
    {name: "William James Moriarty",
    imagePath: "/images/png/william_james_moriarty.png",
    imageAlt: "customer profile image",
    feedback: "This T-Shirt exceeded my expectations! The fabric is soft and comfortable, and the print is vibrant and durable.",
    quoteUpIconPath: "/icons/svg/double-quotes-up.svg",
    quoteUpIconAlt: "double quotes up icon",
    quoteDownIconPath: "/icons/svg/double-quotes-down.svg",
    quoteDownIconAlt: "double quotes down icon",
    starRatingWithoutColorIconPath: "/icons/svg/star-no-color.svg",
    starRatingWithoutColorIconAlt: "star without color icon",
    starRatingWithColorIconPath: "/icons/svg/star-color.svg",
    starRatingWithColorIconAlt: "star with color icon",
    },
]