export const routes = {
    userProtectedRoutes: [
      "/profile",
      "/profile/order-history",
      "/profile/billing",
      "/profile/address",
      "/checkout",
    ],
    protectedApiRoutes: [
      "/api/add-to-cart",
      "/api/get-cart",
      "/api/delete-cart",
      "/api/delete-all-cart",
      "/api/upload-profile-picture",
      "/api/checkout",
      "/api/generate-receipt",
      "/api/csrf",
      "/api/add-to-address-or-billing",
      "/api/update-address-or-billing",
      "/api/delete-address-or-billing",
      "/api/update-order-status-and-tracking-number",
      "/api/upload-product",
      "/api/update-product",
      "/api/add-feedback",
      "/api/request-return",
      "/api/update-return-status",
      "/api/update-account-details",
      "/api/update-user-account",
    ],
    adminProtectedRoutes: [
      "/admin/dashboard",
      "/admin/dashboard/orders",
      "/admin/dashboard/upload-product",
    ],
    passRoutes: [
      "/login",
      "/register",
      "/forgot-password",
      "/reset-password",
      "/admin/login",
    ],
    publicRoutes: [
      "/",
      "/about",
      "/terms-and-conditions",
      "/all-products",
      "/privacy-policy",
    ]
  };